export const templates = [
  {
    id: "t_rest",
    name: "Maison Bistro",
    category: "Restaurant",
    uses: 1240,
    accent: "from-amber-500/50 to-rose-500/30",
  },
  {
    id: "t_gym",
    name: "Ironroot",
    category: "Gym",
    uses: 980,
    accent: "from-lime-400/50 to-emerald-500/30",
  },
  {
    id: "t_dent",
    name: "Marbled Care",
    category: "Dentist",
    uses: 612,
    accent: "from-sky-300/50 to-blue-500/30",
  },
  {
    id: "t_port",
    name: "Atelier",
    category: "Portfolio",
    uses: 2310,
    accent: "from-stone-300/50 to-neutral-500/30",
  },
  {
    id: "t_ecom",
    name: "Northfold",
    category: "Ecommerce",
    uses: 1820,
    accent: "from-fuchsia-500/50 to-rose-500/30",
  },
  {
    id: "t_int",
    name: "Living Room",
    category: "Interior",
    uses: 760,
    accent: "from-orange-400/50 to-amber-500/30",
  },
  {
    id: "t_real",
    name: "Orchard",
    category: "Real Estate",
    uses: 540,
    accent: "from-emerald-400/50 to-lime-400/30",
  },
  {
    id: "t_law",
    name: "Coleman & Vale",
    category: "Lawyer",
    uses: 410,
    accent: "from-zinc-400/50 to-slate-600/30",
  },
  {
    id: "t_doc",
    name: "Mercy Clinic",
    category: "Doctor",
    uses: 380,
    accent: "from-cyan-400/50 to-sky-500/30",
  },
  {
    id: "t_start",
    name: "Liftoff",
    category: "Startup",
    uses: 3010,
    accent: "from-violet-500/50 to-indigo-500/30",
  },
  {
    id: "t_trav",
    name: "Wayfarer",
    category: "Travel",
    uses: 980,
    accent: "from-teal-400/50 to-cyan-500/30",
  },
  {
    id: "t_hot",
    name: "Lumière",
    category: "Hotel",
    uses: 720,
    accent: "from-yellow-300/50 to-amber-500/30",
  },
];

export const examplePrompts = [
  "A candlelit French bistro with online reservations",
  "Brutalist architecture studio portfolio, monochrome",
  "Yoga studio with class schedule and membership tiers",
  "Indie game studio landing page with parallax hero",
  "Boutique hotel in the Dolomites with booking widget",
  "Specialty coffee roaster ecommerce with subscriptions",
];
